"""PR creation via the ``gh`` CLI.

Pushes the worktree's branch to ``origin`` and opens a PR with the spec and
implementation summary in the body. Refuses to apply any reserved labels.
"""

from __future__ import annotations

import shutil
import subprocess
from dataclasses import dataclass
from pathlib import Path

from smithic.config import RESERVED_LABELS, PRConfig
from smithic.worktree.manager import Worktree


class PRError(RuntimeError):
    pass


@dataclass(frozen=True)
class PRResult:
    url: str
    branch: str
    is_draft: bool


def _run(cmd: list[str], cwd: Path) -> subprocess.CompletedProcess[str]:
    result = subprocess.run(
        cmd, cwd=str(cwd), capture_output=True, text=True, shell=False, check=False
    )
    if result.returncode != 0:
        raise PRError(
            f"{' '.join(cmd)} failed in {cwd}: {result.stderr.strip() or result.stdout.strip()}"
        )
    return result


def _sanitize_labels(labels: list[str]) -> list[str]:
    return [label for label in labels if label not in RESERVED_LABELS]


def open_pr(
    *,
    worktree: Worktree,
    title: str,
    body: str,
    pr_config: PRConfig,
    draft: bool,
) -> PRResult:
    """Push the worktree branch and open a PR. Returns the PR URL."""
    if shutil.which("gh") is None:
        raise PRError("gh CLI not found on PATH")

    # Push the branch first. We use --set-upstream so subsequent pushes work.
    _run(
        ["git", "push", "--set-upstream", "origin", worktree.branch],
        cwd=worktree.path,
    )

    cmd: list[str] = [
        "gh",
        "pr",
        "create",
        "--title",
        title,
        "--body",
        body,
        "--base",
        pr_config.base_branch,
        "--head",
        worktree.branch,
    ]
    if draft:
        cmd.append("--draft")
    for label in _sanitize_labels(pr_config.labels):
        cmd.extend(["--label", label])

    result = _run(cmd, cwd=worktree.path)
    url = result.stdout.strip().splitlines()[-1] if result.stdout.strip() else ""
    if not url.startswith("http"):
        raise PRError(f"could not parse PR URL from gh output: {result.stdout!r}")

    return PRResult(url=url, branch=worktree.branch, is_draft=draft)


def compose_pr_body(
    *,
    feature: str,
    mission_excerpt: str,
    impl_summary: str,
    cost_usd: float,
    run_id: str,
) -> str:
    return f"""## Feature

{feature.strip()}

## Mission context

{mission_excerpt.strip()}

## Implementation summary

{impl_summary.strip()}

---

<sub>Generated by [Smithic](https://github.com/code-monkies/Smithic) · run `{run_id}` · ${cost_usd:.4f} spent</sub>
"""
